# ==========================================
# Prescient Linux - Extensible Rules Schema
# ==========================================
# Add or remove packages here to customize what prescient considers "dangerous".
# If a package update contains any of these strings, prescient will trigger a snapshot.

[triggers.high_risk]
kernel = [
    "linux-image", 
    "linux-headers", 
    "linux-lts", 
    "linux-zen", 
    "initramfs-tools", 
    "mkinitcpio",
    "linux-kernel"
]
bootloader = [
    "grub", 
    "grub-efi", 
    "shim", 
    "shim-signed", 
    "systemd-boot"
]
heuristics = ["sudo", "libssh-4", "libssh-gcrypt-4", "libexiv2-27", "snapd"] # Packages dynamically flagged by prescient's Intelligence Engine

[triggers.medium_risk]
drivers = [
    "nvidia", 
    "dkms", 
    "virtualbox", 
    "mesa-vulkan", 
    "amdgpu"
]
display_server = [
    "xserver-xorg", 
    "wayland", 
    "gdm3", 
    "sddm", 
    "lightdm"
]
core_daemons = [
    "systemd", 
    "libc6", 
    "dbus", 
    "glibc"
]